version: '3'
services:
  api:
    build: .
    command: npm start
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - mongo
    environment:
      MONGO_URL: mongodb://mongo:27017/db
      REDIS_URL: redis://redis:6379
  mongo:
    container_name: mongo
    image: mongo:4.4
    ports:
      - "27017:27017"
  redis:
    container_name: redis
    image: redis:6.2
    ports:
      - "6379:6379"